name: CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test